version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/emhub/emhub-js
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install -g
            - run: grunt ts-test
workflows:
    build-and-test:
      jobs:
        - build-and-test
